using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace OcarinaTextEditor.Enums
{
    public enum MsgColor
    {
        W = 0x40,
        R = 0x41,
        G = 0x42,
        B = 0x43,
        C = 0x44,
        M = 0x45,
        Y = 0x46,
        BLK = 0x47
    }

    public enum ControlCode
    {
        LINE_BREAK = 0x01,
        END = 0x02,
        NEW_BOX = 0x04,
        COLOR = 0x05,
        SHIFT = 0x06,
        JUMP = 0x07,
        DI = 0x08,
        DC = 0x09,
        PERSISTENT = 0x0A,
        EVENT = 0x0B,
        DELAY = 0x0C,
        AWAIT_BUTTON = 0x0D,
        FADE = 0x0E,
        PLAYER = 0x0F,
        OCARINA = 0x10,
        FADE2 = 0x11,
        SOUND = 0x12,
        ICON = 0x13,
        SPEED = 0x14,
        BACKGROUND = 0x15,
        MARATHON_TIME = 0x16,
        RACE_TIME = 0x17,
        POINTS = 0x18,
        GOLD_SKULLTULAS = 0x19,
        NS = 0x1A,
        TWO_CHOICES = 0x1B,
        THREE_CHOICES = 0x1C,
        FISH_WEIGHT = 0x1D,
        HIGH_SCORE = 0x1E,
        TIME = 0x1F,

        DASH = 0x7F,
        À = 0x80,
        Î = 0x81,
        Â = 0x82,
        Ä = 0x83,
        Ç = 0x84,
        È = 0x85,
        É = 0x86,
        Ê = 0x87,
        Ë = 0x88,
        Ï = 0x89,
        Ô = 0x8A,
        Ö = 0x8B,
        Ù = 0x8C,
        Û = 0x8D,
        Ü = 0x8E,
        ß = 0x8F,
        à = 0x90,
        á = 0x91,
        â = 0x92,
        ä = 0x93,
        ç = 0x94,
        è = 0x95,
        é = 0x96,
        ê = 0x97,
        ë = 0x98,
        ï = 0x99,
        ô = 0x9A,
        ö = 0x9B,
        ù = 0x9C,
        û = 0x9D,
        ü = 0x9E,

        A_BUTTON = 0x9F,
        B_BUTTON = 0xA0,
        C_BUTTON = 0xA1,
        L_BUTTON = 0xA2,
        R_BUTTON = 0xA3,
        Z_BUTTON = 0xA4,
        C_UP = 0xA5,
        C_DOWN = 0xA6,
        C_LEFT = 0xA7,
        C_RIGHT = 0xA8,
        TRIANGLE = 0xA9,
        CONTROL_STICK = 0xAA,
        D_PAD = 0xAB
    }

    public enum MsgHighScore
    {
        ARCHERY = 0x00,
        POE_POINTS = 0x01,
        FISHING = 0x02,
        HORSE_RACE = 0x03,
        MARATHON = 0x04,
        DAMPE_RACE = 0x06
    }

    public enum MsgIcon
    {
        DEKU_STICK,
        DEKU_NUT,
        BOMBS,
        BOW,
        FIRE_ARROWS,
        DINS_FIRE,
        SLINGSHOT,
        FAIRY_OCARINA,
        OCARINA_OF_TIME,
        BOMBCHUS,
        HOOKSHOT,
        LONGSHOT,
        ICE_ARROWS,
        FARORES_WIND,
        BOOMERANG,
        LENS_OF_TRUTH,
        BEANS,
        MEGATON_HAMMER,
        LIGHT_ARROWS,
        NAYRUS_LOVE,
        EMPTY_BOTTLE,
        RED_POTION,
        GREEN_POTION,
        BLUE_POTION,
        FAIRY,
        FISH,
        MILK,
        RUTOS_LETTER,
        BLUE_FIRE,
        BOTTLE_BUG,
        BOTTLE_POE,
        HALF_MILK,
        BOTTLE_BIGPOE,
        WEIRD_EGG,
        CHICKEN,
        ZELDAS_LETTER,
        KEATON_MASK,
        SKULL_MASK,
        SPOOKY_MASK,
        BUNNY_HOOD,
        GORON_MASK,
        ZORA_MASK,
        GERUDO_MASK,
        MASK_OF_TRUTH,
        SOLD_OUT,
        POCKET_EGG,
        POCKET_CUCCO,
        COJIRO,
        ODD_MUSHROOM,
        ODD_POTION,
        POACHERS_SAW,
        BROKEN_SWORD,
        PRESCRIPTION,
        EYEBALL_FROG,
        EYEDROPS,
        CLAIM_CHECK,
        BOW_FIRE,
        BOW_ICE,
        BOW_LIGHT,
        KOKIRI_SWORD,
        MASTER_SWORD,
        BIGGORON_SWORD,
        DEKU_SHIELD,
        HYLIAN_SHIELD,
        MIRROR_SHIELD,
        KOKIRI_TUNIC,
        GORON_TUNIC,
        ZORA_TUNIC,
        BOOTS,
        IRON_BOOTS,
        HOVER_BOOTS,
        BULLET_BAG,
        BIGGER_BULLET_BAG,
        BIGGEST_BULLET_BAG,
        QUIVER,
        BIG_QUIVER,
        BIGGEST_QUIVER,
        BOMB_BAG,
        BIGGER_BOMB_BAG,
        BIGGEST_BOMB_BAG,
        GORON_BRACELET,
        SILVER_GAUNTLETS,
        GOLDEN_GAUNTLETS,
        ZORA_SCALE,
        GOLDEN_SCALE,
        BROKEN_KNIFE,
        ADULTS_WALLET,
        GIANTS_WALLET,
        DEKU_SEEDS,
        FISHING_ROD,
        NOTHING_1,
        NOTHING_2,
        NOTHING_3,
        NOTHING_4,
        NOTHING_5,
        NOTHING_6,
        NOTHING_7,
        NOTHING_9,
        NOTHING_10,
        NOTHING_11,
        NOTHING_12,
        NOTHING_13,
        FOREST_MEDALLION,
        FIRE_MEDALLION,
        WATER_MEDALLION,
        SPIRIT_MEDALLION,
        SHADOW_MEDALLION,
        LIGHT_MEDALLION,
        KOKIRI_EMERALD,
        GORON_RUBY,
        ZORA_SAPPHIRE,
        STONE_OF_AGONY,
        GERUDO_PASS,
        GOLDEN_SKULLTULA,
        HEART_CONTAINER,
        HEART_PIECE,
        BOSS_KEY,
        COMPASS,
        DUNGEON_MAP,
        SMALL_KEY,
        MAGIC_JAR,
        BIG_MAGIC_JAR,
    }
}
