using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;

namespace OcarinaTextEditor.Enums
{
    public enum MsgColor
    {
        W = 0x40,
        R = 0x41,
        G = 0x42,
        B = 0x43,
        C = 0x44,
        M = 0x45,
        Y = 0x46,
        BLK = 0x47
    }

    public enum ControlCode
    {
        LINE_BREAK = 0x01,
        END = 0x02,
        NEW_BOX = 0x04,
        COLOR = 0x05,
        SHIFT = 0x06,
        JUMP = 0x07,
        DI = 0x08,
        DC = 0x09,
        PERSISTENT = 0x0A,
        EVENT = 0x0B,
        DELAY = 0x0C,
        AWAIT_BUTTON = 0x0D,
        FADE = 0x0E,
        PLAYER = 0x0F,
        OCARINA = 0x10,
        FADE2 = 0x11,
        SOUND = 0x12,
        ICON = 0x13,
        SPEED = 0x14,
        BACKGROUND = 0x15,
        MARATHON_TIME = 0x16,
        RACE_TIME = 0x17,
        POINTS = 0x18,
        GOLD_SKULLTULAS = 0x19,
        NS = 0x1A,
        TWO_CHOICES = 0x1B,
        THREE_CHOICES = 0x1C,
        FISH_WEIGHT = 0x1D,
        HIGH_SCORE = 0x1E,
        TIME = 0x1F,

        DASH = 0x7F,
        À = 0x80,
        Î = 0x81,
        Â = 0x82,
        Ä = 0x83,
        Ç = 0x84,
        È = 0x85,
        É = 0x86,
        Ê = 0x87,
        Ë = 0x88,
        Ï = 0x89,
        Ô = 0x8A,
        Ö = 0x8B,
        Ù = 0x8C,
        Û = 0x8D,
        Ü = 0x8E,
        ß = 0x8F,
        à = 0x90,
        á = 0x91,
        â = 0x92,
        ä = 0x93,
        ç = 0x94,
        è = 0x95,
        é = 0x96,
        ê = 0x97,
        ë = 0x98,
        ï = 0x99,
        ô = 0x9A,
        ö = 0x9B,
        ù = 0x9C,
        û = 0x9D,
        ü = 0x9E,

        A_BUTTON = 0x9F,
        B_BUTTON = 0xA0,
        C_BUTTON = 0xA1,
        L_BUTTON = 0xA2,
        R_BUTTON = 0xA3,
        Z_BUTTON = 0xA4,
        C_UP = 0xA5,
        C_DOWN = 0xA6,
        C_LEFT = 0xA7,
        C_RIGHT = 0xA8,
        TRIANGLE = 0xA9,
        CONTROL_STICK = 0xAA,
        D_PAD = 0xAB
    }

    public enum MsgColorMajora
    {
        D = 0x00,
        R = 0x01,
        G = 0x02,
        B = 0x03,
        Y = 0x04,
        N = 0x05,
        P = 0x06,
        S = 0x07,
        O = 0x08,
    }

    public enum MajoraIcons
    {
        NO_ICON = 0xFE,
        NOTHING = 0x00,
        GREEN_RUPEE = 0x01,
        BLUE_RUPEE = 0x02,
        WHITE_RUPEE_1 = 0x03,
        RED_RUPEE = 0x04,
        PURPLE_RUPEE = 0x05,
        WHITE_RUPEE_2 = 0x06,
        ORANGE_RUPEE = 0x07,
        ADULT_WALLET = 0x08,
        GIANTS_WALLET = 0x09,
        RECOVERY_HEART_1 = 0x0A,
        RECOVERY_HEART_2 = 0x0B,
        PIECE_OF_HEART = 0x0C,
        HEART_CONTAINER = 0x0D,
        SMALL_MAGIC_JAR = 0x0E,
        LARGE_MAGIC_JAR = 0x0F,
        RECOVERY_HEART = 0x10,
        STRAY_FAIRY = 0x11,
        RECOVERY_HEART_3 = 0x12,
        RECOVERY_HEART_4 = 0x13,
        BOMB_1 = 0x14,
        BOMB_2 = 0x15,
        BOMB_3 = 0x16,
        BOMB_4 = 0x17,
        BOMB_5 = 0x18,
        DEKU_STICK = 0x19,
        BOMBCHU = 0x1A,
        BOMB_BAG = 0x1B,
        BIG_BOMB_BAG = 0x1C,
        BIGGER_BOMB_BAG = 0x1D,
        HEROS_BOW_1 = 0x1E,
        HEROS_BOW_2 = 0x1F,
        HEROS_BOW_3 = 0x20,
        HEROS_BOW_4 = 0x21,
        QUIVER = 0x22,
        BIG_QUIVER = 0x23,
        BIGGEST_QUIVER = 0x24,
        FIRE_ARROW = 0x25,
        ICE_ARROW = 0x26,
        LIGHT_ARROW = 0x27,
        DEKU_NUT_1 = 0x28,
        DEKU_NUT_2 = 0x29,
        DEKU_NUT_3 = 0x2A,
        HEROS_SHIELD = 0x32,
        MIRROR_SHIELD = 0x33,
        POWDER_KEG_1 = 0x34,
        MAGIC_BEAN = 0x35,
        PICTOGRAPH_BOX_1 = 0x36,
        KOKIRI_SWORD = 0x37,
        RAZOR_SWORD = 0x38,
        GILDED_SWORD = 0x39,
        FIERCE_DEITYS_SWORD = 0x3A,
        GREAT_FAIRYS_SWORD = 0x3B,
        SMALL_KEY = 0x3C,
        BOSS_KEY = 0x3D,
        DUNGEON_MAP = 0x3E,
        COMPASS = 0x3F,
        POWDER_KEG_2 = 0x40,
        HOOKSHOT = 0x41,
        LENS_OF_TRUTH = 0x42,
        PICTOGRAPH_BOX_2 = 0x43,
        FISHING_ROD = 0x44,
        OCARINA_OF_TIME = 0x4C,
        BOMBERS_NOTEBOOK = 0x50,
        GOLD_SKULLTULA_TOKEN = 0x52,
        ODOLWAS_REMAINS = 0x55,
        GOHTS_REMAINS = 0x56,
        GYORGS_REMAINS = 0x57,
        TWINMOLDS_REMAINS = 0x58,
        RED_POTION_1 = 0x59,
        EMPTY_BOTTLE = 0x5A,
        RED_POTION_2 = 0x5B,
        GREEN_POTION = 0x5C,
        BLUE_POTION = 0x5D,
        FAIRYS_SPIRIT = 0x5E,
        DEKU_PRINCESS = 0x5F,
        MILK_1 = 0x60,
        MILK_HALF = 0x61,
        FISH = 0x62,
        BUG = 0x63,
        BLUE_FIRE = 0x64,
        POE = 0x65,
        BIG_POE = 0x66,
        SPRING_WATER = 0x67,
        HOT_SPRING_WATER = 0x68,
        ZORA_EGG = 0x69,
        GOLD_DUST_1 = 0x6A,
        MUSHROOM = 0x6B,
        SEAHORSE_1 = 0x6E,
        CHATEAU_ROMANI_1 = 0x6F,
        HYLIAN_LOACH_1 = 0x70,
        DEKU_MASK = 0x78,
        GORON_MASK = 0x79,
        ZORA_MASK = 0x7A,
        FIERCE_DEITY_MASK = 0x7B,
        MASK_OF_TRUTH = 0x7C,
        KAFEIS_MASK = 0x7D,
        ALL_NIGHT_MASK = 0x7E,
        BUNNY_HOOD = 0x7F,
        KEATON_MASK = 0x80,
        GARO_MASK = 0x81,
        ROMANI_MASK = 0x82,
        CIRCUS_LEADERS_MASK = 0x83,
        POSTMANS_HAT = 0x84,
        COUPLES_MASK = 0x85,
        GREAT_FAIRYS_MASK = 0x86,
        GIBDO_MASK = 0x87,
        DON_GEROS_MASK = 0x88,
        KAMAROS_MASK = 0x89,
        CAPTAINS_HAT = 0x8A,
        STONE_MASK = 0x8B,
        BREMEN_MASK = 0x8C,
        BLAST_MASK = 0x8D,
        MASK_OF_SCENTS = 0x8E,
        GIANTS_MASK = 0x8F,
        CHATEAU_ROMANI_2 = 0x91,
        MILK_2 = 0x92,
        GOLD_DUST_2 = 0x93,
        HYLIAN_LOACH_2 = 0x94,
        SEAHORSE_2 = 0x95,
        MOONS_TEAR = 0x96,
        TOWN_TITLE_DEED = 0x97,
        SWAMP_TITLE_DEED = 0x98,
        MOUNTAIN_TITLE_DEED = 0x99,
        OCEAN_TITLE_DEED = 0x9A,
        ROOM_KEY = 0xA0,
        SPECIAL_DELIVERY_TO_MAMA = 0xA1,
        LETTER_TO_KAFEI = 0xAA,
        PENDANT_OF_MEMORIES = 0xAB,
        TINGLE_MAP_1 = 0xB3,
        TINGLE_MAP_2 = 0xB4,
        TINGLE_MAP_3 = 0xB5,
        TINGLE_MAP_4 = 0xB6,
        TINGLE_MAP_5 = 0xB7,
        TINGLE_MAP_6 = 0xB8,
        TINGLE_MAP_7 = 0xB9,
        SMALL_BLACK_LINE = 0xD8,
        ANJU = 0xDC,
        KAFEI = 0xDD,
        CURIOSITY_SHOP_OWNER = 0xDE,
        BOMB_SHOP_OWNERS_MOTHER = 0xDF,
        ROMANI = 0xE0,
        CREMIA = 0xE1,
        MAYOR_DOTOUR = 0xE2,
        MADAME_AROMA = 0xE3,
        TOTO = 0xE4,
        GORMAN = 0xE5,
        POSTMAN = 0xE6,
        ROSA_SISTERS = 0xE7,
        TOILET_HAND = 0xE8,
        GRANNY = 0xE9,
        KAMARO = 0xEA,
        GROG = 0xEB,
        GORMAN_BROTHERS = 0xEC,
        SHIRO = 0xED,
        GURUGURU = 0xEE,
        BOMBERS = 0xEF,
        EXCLAMATION_MARK = 0xF0,
    }

    public enum MajoraControlCode
    {
        COLOR_DEFAULT = 0x00,
        COLOR_RED = 0x01,
        COLOR_GREEN = 0x02,
        COLOR_BLUE = 0x03,
        COLOR_YELLOW = 0x04,
        COLOR_NAVY = 0x05,
        COLOR_PINK = 0x06,
        COLOR_SILVER = 0x07,
        COLOR_ORANGE = 0x08,
        UNK_09 = 0x09,
        SLOW_TEXT = 0x0A,
        SWAMP_CRUISE_HITS = 0x0B,
        STRAY_FAIRY_SCORE = 0x0C,
        GOLD_SKULLTULAS = 0x0D,
        UNK_0E = 0xE,
        UNK_0F = 0xF,
        NEW_BOX = 0x10,
        LINE_BREAK = 0x11,
        NEW_BOX_INCOMPL = 0x12,
        RESET_CURSOR = 0x13,
        SHIFT = 0x14,
        NOSKIP = 0x15,
        PLAYER = 0x16,
        DI = 0x17,
        DC = 0x18,
        NOSKIP_SOUND = 0x19,
        PERSISTENT = 0x1A,
        DELAY_DI = 0x1B,
        FADE = 0x1C,
        DELAY_END = 0x1D,
        SOUND = 0x1E,
        DELAY_DC = 0x1F,
        END = 0xBF,
        BACKGROUND = 0xC1,
        TWO_CHOICES = 0xC2,
        THREE_CHOICES = 0xC3,
        POSTMAN_RESULTS = 0xC4,
        TIMER = 0xC5,
        TIMER2 = 0xC6,
        MOON_CRASH_TIME = 0xC7,
        DEKU_RESULTS = 0xC8,
        TIMER3 = 0xC9,
        TIMER4 = 0xCA,
        SHOOTING_GALLERY_RESULT = 0xCB,
        BANK_PROMPT = 0xCC,
        RUPEES_ENTERED = 0xCD,
        RUPEES_IN_BANK = 0xCE,
        TIME_REMAINING = 0xCF,
        BET_RUPEES = 0xD0,
        PROMPT_BOMBER_CODE = 0xD1,
        ITEM_PROMPT = 0xD2,
        UNK_D3 = 0xD3,
        SOARING_DESTINATION = 0xD4,
        LOTTERY_NUMBER = 0xD5,
        UNK_D6 = 0xD6,
        WOODFALL_FAIRIES_REMAIN = 0xD7,
        SNOWHEAD_FAIRIES_REMAIN = 0xD8,
        BAY_FAIRIES_REMAIN = 0xD9,
        IKANA_FAIRIES_REMAIN = 0xDA,
        SWAMP_CRUISE_RESULT = 0xDB,
        WINNING_LOTTERY_NUM = 0xDC,
        PLAYER_LOTTERY_NUM = 0xDD,
        ITEM_VALUE = 0xDE,
        BOMBER_CODE = 0xDF,
        END_CONVERSATION = 0xE0,
        OCEAN_SKULLTULA_MASK1 = 0xE1,
        OCEAN_SKULLTULA_MASK2 = 0xE2,
        OCEAN_SKULLTULA_MASK3 = 0xE3,
        OCEAN_SKULLTULA_MASK4 = 0xE4,
        OCEAN_SKULLTULA_MASK5 = 0xE5,
        OCEAN_SKULLTULA_MASK6 = 0xE6,
        MOON_CRASH_TIME_HHMM = 0xE7,
        UNTIL_MORNING = 0xE8,
        UNK_E9 = 0xE9,
        UNK_EA = 0xEA,
        UNK_EB = 0xEB,
        UNK_EC = 0xEC,
        UNK_ED = 0xED,
        UNK_EE = 0xEE,
        UNK_EF = 0xEF,
        TOTAL_IN_BANK = 0xF0,
        UNK_F1 = 0xF1,
        UNK_F2 = 0xF2,
        UNK_F3 = 0xF3,
        UNK_F4 = 0xF4,
        UNK_F5 = 0xF5,
        TOWN_SHOOTING_HIGHSCORE = 0xF6,
        UNK_F7 = 0xF7,
        UNK_F8 = 0xF8,
        EPONA_ARCHERY_HIGHSCORE = 0xF9,
        DEKU_HIGHSCORE_DAY1 = 0xFA,
        DEKU_HIGHSCORE_DAY2 = 0xFB,
        DEKU_HIGHSCORE_DAY3 = 0xFC,
        UNK_FD = 0xFD,
        UNK_FE = 0xFE,
        UNK_FF = 0xFF,


        DASH = 0x7F,
        À = 0x80,
        Î = 0x81,
        Â = 0x82,
        Ä = 0x83,
        Ç = 0x84,
        È = 0x85,
        É = 0x86,
        Ê = 0x87,
        Ë = 0x88,
        Ï = 0x89,
        Ô = 0x8A,
        Ö = 0x8B,
        Ù = 0x8C,
        Û = 0x8D,
        Ü = 0x8E,
        ß = 0x8F,
        à = 0x90,
        á = 0x91,
        â = 0x92,
        ä = 0x93,
        ç = 0x94,
        è = 0x95,
        é = 0x96,
        ê = 0x97,
        ë = 0x98,
        ï = 0x99,
        ô = 0x9A,
        ö = 0x9B,
        ù = 0x9C,
        û = 0x9D,
        ü = 0x9E,

        A_BUTTON = 0xB0,
        B_BUTTON = 0xB1,
        C_BUTTON = 0xB2,
        L_BUTTON = 0xB3,
        R_BUTTON = 0xB4,
        Z_BUTTON = 0xB5,
        C_UP = 0xB6,
        C_DOWN = 0xB7,
        C_LEFT = 0xB8,
        C_RIGHT = 0xB9,
        TRIANGLE = 0xBA,
        CONTROL_STICK = 0xBB,
        D_PAD = 0xBC
    }

    public enum MsgHighScore
    {
        ARCHERY = 0x00,
        POE_POINTS = 0x01,
        FISHING = 0x02,
        HORSE_RACE = 0x03,
        MARATHON = 0x04,
        HS_UNK = 0x05,
        DAMPE_RACE = 0x06
    }

    public enum MsgIcon
    {
        DEKU_STICK,
        DEKU_NUT,
        BOMBS,
        BOW,
        FIRE_ARROWS,
        DINS_FIRE,
        SLINGSHOT,
        FAIRY_OCARINA,
        OCARINA_OF_TIME,
        BOMBCHUS,
        HOOKSHOT,
        LONGSHOT,
        ICE_ARROWS,
        FARORES_WIND,
        BOOMERANG,
        LENS_OF_TRUTH,
        BEANS,
        MEGATON_HAMMER,
        LIGHT_ARROWS,
        NAYRUS_LOVE,
        EMPTY_BOTTLE,
        RED_POTION,
        GREEN_POTION,
        BLUE_POTION,
        FAIRY,
        FISH,
        MILK,
        RUTOS_LETTER,
        BLUE_FIRE,
        BOTTLE_BUG,
        BOTTLE_POE,
        HALF_MILK,
        BOTTLE_BIGPOE,
        WEIRD_EGG,
        CHICKEN,
        ZELDAS_LETTER,
        KEATON_MASK,
        SKULL_MASK,
        SPOOKY_MASK,
        BUNNY_HOOD,
        GORON_MASK,
        ZORA_MASK,
        GERUDO_MASK,
        MASK_OF_TRUTH,
        SOLD_OUT,
        POCKET_EGG,
        POCKET_CUCCO,
        COJIRO,
        ODD_MUSHROOM,
        ODD_POTION,
        POACHERS_SAW,
        BROKEN_SWORD,
        PRESCRIPTION,
        EYEBALL_FROG,
        EYEDROPS,
        CLAIM_CHECK,
        BOW_FIRE,
        BOW_ICE,
        BOW_LIGHT,
        KOKIRI_SWORD,
        MASTER_SWORD,
        BIGGORON_SWORD,
        DEKU_SHIELD,
        HYLIAN_SHIELD,
        MIRROR_SHIELD,
        KOKIRI_TUNIC,
        GORON_TUNIC,
        ZORA_TUNIC,
        BOOTS,
        IRON_BOOTS,
        HOVER_BOOTS,
        BULLET_BAG,
        BIGGER_BULLET_BAG,
        BIGGEST_BULLET_BAG,
        QUIVER,
        BIG_QUIVER,
        BIGGEST_QUIVER,
        BOMB_BAG,
        BIGGER_BOMB_BAG,
        BIGGEST_BOMB_BAG,
        GORON_BRACELET,
        SILVER_GAUNTLETS,
        GOLDEN_GAUNTLETS,
        ZORA_SCALE,
        GOLDEN_SCALE,
        BROKEN_KNIFE,
        ADULTS_WALLET,
        GIANTS_WALLET,
        DEKU_SEEDS,
        FISHING_ROD,
        NOTHING_1,
        NOTHING_2,
        NOTHING_3,
        NOTHING_4,
        NOTHING_5,
        NOTHING_6,
        NOTHING_7,
        NOTHING_9,
        NOTHING_10,
        NOTHING_11,
        NOTHING_12,
        NOTHING_13,
        FOREST_MEDALLION,
        FIRE_MEDALLION,
        WATER_MEDALLION,
        SPIRIT_MEDALLION,
        SHADOW_MEDALLION,
        LIGHT_MEDALLION,
        KOKIRI_EMERALD,
        GORON_RUBY,
        ZORA_SAPPHIRE,
        STONE_OF_AGONY,
        GERUDO_PASS,
        GOLDEN_SKULLTULA,
        HEART_CONTAINER,
        HEART_PIECE,
        BOSS_KEY,
        COMPASS,
        DUNGEON_MAP,
        SMALL_KEY,
        MAGIC_JAR,
        BIG_MAGIC_JAR,
    }
}
